# print("==================================")
# print("Nama: safaridin")
# print("Kelas: 19.1A.24")
# print("Jurusan: SIstem Informasi")
# print("==================================")

print ("===========================================")
print ("Nama : David Sandiva")
print ("Kelas : 19.1A.24")
print ("Jurusan : Sistem Informasi")
print ("===========================================")